/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import teste.Despesa;
import javax.swing.ImageIcon;

/**
 *
 * @author csnas
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        abas.setEnabledAt(1, false);
        abas.setEnabledAt(2, false);
        abas.setEnabledAt(3, false);
        txtTotal.setEditable(false);
        txtSaldoFinal.setEditable(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        abas = new javax.swing.JTabbedPane();
        inicio = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        lblImg = new javax.swing.JLabel();
        cadastro = new javax.swing.JPanel();
        lblOrcamento = new javax.swing.JLabel();
        txtValorOrcamento = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblCategoria = new javax.swing.JLabel();
        boxCategoria = new javax.swing.JComboBox<>();
        lblTipoDespesa = new javax.swing.JLabel();
        boxTipoDespesa = new javax.swing.JComboBox<>();
        lblValor = new javax.swing.JLabel();
        txtValorDespesa = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        listagem = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListagem = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        txtSaldoFinal = new javax.swing.JTextField();
        lblValorTotal = new javax.swing.JLabel();
        lblSaldoFinal = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblCategoria1 = new javax.swing.JLabel();
        boxCategoria1 = new javax.swing.JComboBox<>();
        lblTipoDespesa1 = new javax.swing.JLabel();
        boxTipoDespesa1 = new javax.swing.JComboBox<>();
        lblValor1 = new javax.swing.JLabel();
        txtValorDespesa1 = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        abas.setBackground(new java.awt.Color(255, 255, 255));
        abas.setForeground(new java.awt.Color(0, 0, 0));
        abas.setToolTipText("");
        abas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        inicio.setBackground(new java.awt.Color(255, 255, 255));
        inicio.setLayout(null);

        lblTitulo.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(102, 153, 255));
        lblTitulo.setText("PLANEJADOR DE DESPESAS SQUAD 5");
        inicio.add(lblTitulo);
        lblTitulo.setBounds(90, 0, 440, 40);

        btnIniciar.setBackground(new java.awt.Color(255, 255, 255));
        btnIniciar.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(102, 153, 255));
        btnIniciar.setText("INICIAR");
        btnIniciar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(169, 246, 255), null));
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        inicio.add(btnIniciar);
        btnIniciar.setBounds(270, 40, 110, 40);

        lblImg.setIcon(new ImageIcon("C:\\Users\\csnas\\eclipse-workspace\\Planejador-De-Despesas\\src\\view\\img.jpg")); // NOI18N
        lblImg.setText("jLabel2");
        inicio.add(lblImg);
        lblImg.setBounds(70, 40, 492, 332);

        abas.addTab("Início", inicio);

        cadastro.setBackground(new java.awt.Color(255, 255, 255));

        lblOrcamento.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        lblOrcamento.setForeground(new java.awt.Color(51, 51, 51));
        lblOrcamento.setText("Orçamento:");

        txtValorOrcamento.setBackground(new java.awt.Color(255, 255, 255));
        txtValorOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorOrcamentoActionPerformed(evt);
            }
        });
        txtValorOrcamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorOrcamentoKeyTyped(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null), "Cadastrar Despesa:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Demi", 0, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        lblCategoria.setBackground(new java.awt.Color(51, 51, 51));
        lblCategoria.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCategoria.setForeground(new java.awt.Color(51, 51, 51));
        lblCategoria.setText("Categoria: ");

        boxCategoria.setBackground(new java.awt.Color(255, 255, 255));
        boxCategoria.setForeground(new java.awt.Color(51, 51, 51));
        boxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>", "Compras", "Contas", "Lazer", "Viagem", "Outros" }));
        boxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxCategoriaActionPerformed(evt);
            }
        });

        lblTipoDespesa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTipoDespesa.setForeground(new java.awt.Color(51, 51, 51));
        lblTipoDespesa.setText("Tipo de Despesa: ");

        boxTipoDespesa.setBackground(new java.awt.Color(255, 255, 255));
        boxTipoDespesa.setForeground(new java.awt.Color(51, 51, 51));
        boxTipoDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTipoDespesaActionPerformed(evt);
            }
        });

        lblValor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValor.setForeground(new java.awt.Color(51, 51, 51));
        lblValor.setText("Valor: ");

        txtValorDespesa.setBackground(new java.awt.Color(255, 255, 255));
        txtValorDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorDespesaActionPerformed(evt);
            }
        });
        txtValorDespesa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorDespesaKeyTyped(evt);
            }
        });

        btnCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setForeground(new java.awt.Color(51, 51, 51));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new ImageIcon("C:\\Users\\csnas\\eclipse-workspace\\Planejador-De-Despesas\\src\\view\\7849.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(lblValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtValorDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTipoDespesa)
                                    .addComponent(lblCategoria, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(boxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boxTipoDespesa, 0, 131, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {boxCategoria, boxTipoDespesa});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCategoria)
                            .addComponent(boxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoDespesa)
                            .addComponent(boxTipoDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValorDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValor))
                        .addGap(47, 47, 47)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {boxCategoria, boxTipoDespesa, txtValorDespesa});

        javax.swing.GroupLayout cadastroLayout = new javax.swing.GroupLayout(cadastro);
        cadastro.setLayout(cadastroLayout);
        cadastroLayout.setHorizontalGroup(
            cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroLayout.createSequentialGroup()
                .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblOrcamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cadastroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cadastroLayout.setVerticalGroup(
            cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtValorOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrcamento))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        abas.addTab("Cadastro", cadastro);

        listagem.setBackground(new java.awt.Color(255, 255, 255));

        tblListagem.setBackground(new java.awt.Color(255, 255, 255));
        tblListagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categoria", "Tipo", "Valor"
            }
        ));
        jScrollPane1.setViewportView(tblListagem);

        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar.setForeground(new java.awt.Color(51, 51, 51));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(255, 255, 255));
        btnExcluir.setForeground(new java.awt.Color(51, 51, 51));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        txtTotal.setBackground(new java.awt.Color(255, 255, 255));
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        txtSaldoFinal.setBackground(new java.awt.Color(255, 255, 255));
        txtSaldoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoFinalActionPerformed(evt);
            }
        });

        lblValorTotal.setForeground(new java.awt.Color(51, 51, 51));
        lblValorTotal.setText("Total:");

        lblSaldoFinal.setForeground(new java.awt.Color(51, 51, 51));
        lblSaldoFinal.setText("Saldo Final:");

        btnCalcular.setBackground(new java.awt.Color(255, 255, 255));
        btnCalcular.setForeground(new java.awt.Color(51, 51, 51));
        btnCalcular.setText("Efetuar Cálculo");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listagemLayout = new javax.swing.GroupLayout(listagem);
        listagem.setLayout(listagemLayout);
        listagemLayout.setHorizontalGroup(
            listagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listagemLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(listagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listagemLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(listagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listagemLayout.createSequentialGroup()
                                .addComponent(lblSaldoFinal)
                                .addGap(47, 47, 47))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listagemLayout.createSequentialGroup()
                                .addComponent(lblValorTotal)
                                .addGap(62, 62, 62))))
                    .addGroup(listagemLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(listagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(listagemLayout.createSequentialGroup()
                                .addComponent(btnCalcular)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(listagemLayout.createSequentialGroup()
                                .addGroup(listagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                    .addComponent(txtSaldoFinal))
                                .addGap(17, 17, 17))
                            .addGroup(listagemLayout.createSequentialGroup()
                                .addGroup(listagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );

        listagemLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCalcular, btnEditar, btnExcluir});

        listagemLayout.setVerticalGroup(
            listagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listagemLayout.createSequentialGroup()
                .addGroup(listagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(listagemLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCalcular)
                        .addGap(17, 17, 17)
                        .addComponent(lblValorTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSaldoFinal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSaldoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(listagemLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        listagemLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCalcular, btnEditar, btnExcluir});

        abas.addTab("Listagem", listagem);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null), "Editar Despesa:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Demi", 0, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        lblCategoria1.setBackground(new java.awt.Color(51, 51, 51));
        lblCategoria1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCategoria1.setForeground(new java.awt.Color(51, 51, 51));
        lblCategoria1.setText("Categoria: ");

        boxCategoria1.setBackground(new java.awt.Color(255, 255, 255));
        boxCategoria1.setForeground(new java.awt.Color(51, 51, 51));
        boxCategoria1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>", "Compras", "Contas", "Lazer", "Viagem" }));
        boxCategoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxCategoria1ActionPerformed(evt);
            }
        });

        lblTipoDespesa1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTipoDespesa1.setForeground(new java.awt.Color(51, 51, 51));
        lblTipoDespesa1.setText("Tipo de Despesa: ");

        boxTipoDespesa1.setBackground(new java.awt.Color(255, 255, 255));
        boxTipoDespesa1.setForeground(new java.awt.Color(51, 51, 51));
        boxTipoDespesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTipoDespesa1ActionPerformed(evt);
            }
        });

        lblValor1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValor1.setForeground(new java.awt.Color(51, 51, 51));
        lblValor1.setText("Valor: ");

        txtValorDespesa1.setBackground(new java.awt.Color(255, 255, 255));
        txtValorDespesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorDespesa1ActionPerformed(evt);
            }
        });
        txtValorDespesa1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorDespesa1KeyTyped(evt);
            }
        });

        btnAlterar.setBackground(new java.awt.Color(255, 255, 255));
        btnAlterar.setForeground(new java.awt.Color(51, 51, 51));
        btnAlterar.setText("Editar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new ImageIcon("C:\\Users\\csnas\\eclipse-workspace\\Planejador-De-Despesas\\src\\view\\6962043.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblTipoDespesa1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(boxTipoDespesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblValor1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtValorDespesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblCategoria1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoria1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoDespesa1)
                    .addComponent(boxTipoDespesa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor1)
                    .addComponent(txtValorDespesa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        abas.addTab("", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abas))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abas))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        abas.setEnabledAt(1, true);
        abas.setSelectedIndex(1);
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        if (txtValorOrcamento.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, insira o valor do orçamento!");
            return;
        }
        if (boxCategoria.getSelectedItem() == "<Selecione>") {
            JOptionPane.showMessageDialog(null, "Por favor, selecione a categoria da despesa");
            return;
        }
        if (txtValorDespesa.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, insira o valor da despesa!");
            return;
        }

        abas.setEnabledAt(2, true);
        int a;
        a = JOptionPane.showConfirmDialog(null, "Deseja cadastrar Despesa?", "Cadastrar",
                JOptionPane.YES_NO_OPTION);

        if (a == JOptionPane.YES_OPTION) {
            if(txtValorOrcamento.getText().trim().equals("")) {
                txtValorOrcamento.setEditable(true);
            } else {
                txtValorOrcamento.setEditable(false);
            }
            
            Integer nomeDespesa = boxCategoria.getSelectedIndex();
            String tipoDespesa = (String) boxTipoDespesa.getSelectedItem();
            Double valorDespesa = Double.parseDouble(txtValorDespesa.getText());
            Despesa des = new Despesa();

            des.cadastrarDespesa(tipoDespesa, nomeDespesa, valorDespesa);

            JOptionPane.showMessageDialog(null, "Despesa cadastrada com sucesso!");

            String categoria = (String) boxCategoria.getSelectedItem();
            String tipoDesp = (String) boxTipoDespesa.getSelectedItem();
            String valor = txtValorDespesa.getText();

            DefaultTableModel tbListagem = (DefaultTableModel) tblListagem.getModel();
            tbListagem.addRow(new String[]{categoria, tipoDesp, valor});

            boxCategoria.setSelectedItem("<Selecione>");
            txtValorDespesa.setText("");

            int b = JOptionPane.showConfirmDialog(null, "Deseja cadastrar nova Despesa?", "Novo",
                    JOptionPane.YES_NO_OPTION);

            if (b == JOptionPane.NO_OPTION) {
                abas.setSelectedIndex(2);

                des.visualizarDespesa();

            }
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtValorDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorDespesaActionPerformed

    }//GEN-LAST:event_txtValorDespesaActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if ((tblListagem.getSelectedRowCount() == 0)) {
            JOptionPane.showMessageDialog(null, "Selecione a linha que deseja Editar!!");
            return;
        }

        int cont = tblListagem.getRowCount();

        String categoria = null, tipoDespesa = null, valor = null;

        for (int i = 0; i < cont; i++) {
            categoria = (String) tblListagem.getValueAt(i, 0);
            tipoDespesa = (String) tblListagem.getValueAt(i, 1);
            valor = (String) tblListagem.getValueAt(i, 2);

        }

        boxCategoria1.setSelectedItem(categoria);
        boxTipoDespesa1.setSelectedItem(tipoDespesa);
        txtValorDespesa1.setText(valor);

        Despesa des = new Despesa();

        des.verificaDespesa(tipoDespesa);

        abas.setSelectedIndex(3);

        ((DefaultTableModel) tblListagem.getModel()).removeRow(tblListagem.getSelectedRow());


    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtSaldoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoFinalActionPerformed

    private void boxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxCategoriaActionPerformed

        if (boxCategoria.getSelectedItem() == "<Selecione>") {
            boxTipoDespesa.removeAllItems();

        } else {
            switch ((String) boxCategoria.getSelectedItem()) {

                case "Compras":
                    boxTipoDespesa.removeAllItems();
                    boxTipoDespesa.addItem("Roupas");
                    boxTipoDespesa.addItem("Calçados");
                    boxTipoDespesa.addItem("Cosméticos");
                    break;

                case "Contas":
                    boxTipoDespesa.removeAllItems();
                    boxTipoDespesa.addItem("Água");
                    boxTipoDespesa.addItem("Energia");
                    boxTipoDespesa.addItem("Mercado");
                    boxTipoDespesa.addItem("Gás");
                    break;

                case "Lazer":
                    boxTipoDespesa.removeAllItems();
                    boxTipoDespesa.addItem("Cinema");
                    boxTipoDespesa.addItem("Shows");
                    boxTipoDespesa.addItem("Outros");
                    break;

                case "Viagem":
                    boxTipoDespesa.removeAllItems();
                    boxTipoDespesa.addItem("Transporte");
                    boxTipoDespesa.addItem("Hospedagem");
                    boxTipoDespesa.addItem("Passeios");
                    break;

                case "Outros":
                    boxTipoDespesa.removeAllItems();
                    boxTipoDespesa.addItem("Outros");
                    break;
            }
        }

    }//GEN-LAST:event_boxCategoriaActionPerformed

    private void boxCategoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxCategoria1ActionPerformed
        if (boxCategoria1.getSelectedItem() == "<Selecione>") {
            boxTipoDespesa1.removeAllItems();

        } else {
            switch ((String) boxCategoria1.getSelectedItem()) {

                case "Compras":
                    boxTipoDespesa1.removeAllItems();
                    boxTipoDespesa1.addItem("Roupas");
                    boxTipoDespesa1.addItem("Calçados");
                    boxTipoDespesa1.addItem("Cosméticos");
                    break;

                case "Contas":
                    boxTipoDespesa1.removeAllItems();
                    boxTipoDespesa1.addItem("Água");
                    boxTipoDespesa1.addItem("Energia");
                    boxTipoDespesa1.addItem("Mercado");
                    boxTipoDespesa1.addItem("Gás");
                    break;

                case "Lazer":
                    boxTipoDespesa1.removeAllItems();
                    boxTipoDespesa1.addItem("Cinema");
                    boxTipoDespesa1.addItem("Shows");
                    boxTipoDespesa1.addItem("Outros");
                    break;

                case "Viagem":
                    boxTipoDespesa1.removeAllItems();
                    boxTipoDespesa1.addItem("Transporte");
                    boxTipoDespesa1.addItem("Hospedagem");
                    boxTipoDespesa1.addItem("Passeios");
                    break;
            }
        }
     }//GEN-LAST:event_boxCategoria1ActionPerformed

    private void txtValorDespesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorDespesa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorDespesa1ActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

        String categoria = (String) boxCategoria1.getSelectedItem();
        String tipoDesp = (String) boxTipoDespesa1.getSelectedItem();
        String valor = txtValorDespesa1.getText();
        Integer nomeDesp = boxCategoria1.getSelectedIndex();
        Double valor1 = Double.parseDouble(txtValorDespesa1.getText());

        Despesa des = new Despesa();

        if (boxCategoria1.getSelectedItem() == "<Selecione>") {
            JOptionPane.showMessageDialog(null, "Por favor, selecione a categoria da despesa!");
            return;
        }
        if (boxTipoDespesa1.getSelectedItem() == "") {
            JOptionPane.showMessageDialog(null, "Por favor, insira o tipo da despesa!");
            return;
        }
        if (txtValorDespesa1.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, insira o valor da despesa!");
            return;
        }

        DefaultTableModel tbListagem = (DefaultTableModel) tblListagem.getModel();
        tbListagem.addRow(new String[]{categoria, tipoDesp, valor});

        boxCategoria1.setSelectedItem("<Selecione>");
        txtValorDespesa1.setText("");

        abas.setSelectedIndex(2);

        des.alterarDespesa(tipoDesp, valor1, nomeDesp);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void boxTipoDespesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTipoDespesa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxTipoDespesa1ActionPerformed

    private void boxTipoDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTipoDespesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxTipoDespesaActionPerformed

    private void txtValorOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorOrcamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorOrcamentoActionPerformed

    private void txtValorOrcamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorOrcamentoKeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && (c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE
                && c != KeyEvent.VK_ENTER && c != KeyEvent.VK_PERIOD)) {

            evt.consume();
            JOptionPane.showMessageDialog(this, "Digite apenas números");

            txtValorOrcamento.setText("");
        }
    }//GEN-LAST:event_txtValorOrcamentoKeyTyped

    private void txtValorDespesaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorDespesaKeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && (c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE
                && c != KeyEvent.VK_ENTER && c != KeyEvent.VK_PERIOD)) {

            evt.consume();
            JOptionPane.showMessageDialog(this, "Digite apenas números");

            txtValorDespesa.setText("");
        }
    }//GEN-LAST:event_txtValorDespesaKeyTyped

    private void txtValorDespesa1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorDespesa1KeyTyped
    char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && (c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE
                && c != KeyEvent.VK_ENTER && c != KeyEvent.VK_PERIOD)) {

            evt.consume();
            JOptionPane.showMessageDialog(this, "Digite apenas números");

            txtValorDespesa1.setText("");
        }
    }//GEN-LAST:event_txtValorDespesa1KeyTyped

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
       int cont = tblListagem.getRowCount();
       double soma = 0;
       
       try {
        for(int i = 0; i < cont; i++) {
            soma += Double.parseDouble(tblListagem.getValueAt(i, 2).toString());
        }
        
        txtTotal.setText(String.valueOf(soma));
        
        Despesa des = new Despesa();
        
        double total = des.calculaDespesa(Double.parseDouble(txtValorOrcamento.getText()));
        txtSaldoFinal.setText(String.valueOf(total));
       

        
       } catch(NumberFormatException e) {
           JOptionPane.showMessageDialog(null, "Erro ao calcular");
       }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
     Despesa des = new Despesa(); 
      if ((tblListagem.getSelectedRowCount() == 0)) {
            JOptionPane.showMessageDialog(null, "Selecione a linha que deseja Excluir!!");
            return;
        }
      int cont = tblListagem.getRowCount();

        String categoria = null, tipoDespesa = null, valor = null;

        for (int i = 0; i < cont; i++) {
            categoria = (String) tblListagem.getValueAt(i, 0);
            tipoDespesa = (String) tblListagem.getValueAt(i, 1);
            valor = (String) tblListagem.getValueAt(i, 2);

        }
     des.excluirDespesa(tipoDespesa);
     
     ((DefaultTableModel) tblListagem.getModel()).removeRow(tblListagem.getSelectedRow());
     
     JOptionPane.showMessageDialog(null, "Despesa excluída com sucesso!");

     
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abas;
    private javax.swing.JComboBox<String> boxCategoria;
    private javax.swing.JComboBox<String> boxCategoria1;
    private javax.swing.JComboBox<String> boxTipoDespesa;
    private javax.swing.JComboBox<String> boxTipoDespesa1;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JPanel cadastro;
    private javax.swing.JPanel inicio;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCategoria1;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblOrcamento;
    private javax.swing.JLabel lblSaldoFinal;
    private javax.swing.JLabel lblTipoDespesa;
    private javax.swing.JLabel lblTipoDespesa1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblValor1;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JPanel listagem;
    private javax.swing.JTable tblListagem;
    private javax.swing.JTextField txtSaldoFinal;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtValorDespesa;
    private javax.swing.JTextField txtValorDespesa1;
    private javax.swing.JTextField txtValorOrcamento;
    // End of variables declaration//GEN-END:variables
}
